<?php
/**
 * @file
 * Code for the ia_admin_views feature.
 */

include_once 'ia_admin_views.features.inc';

/**
 * Implements hook_views_pre_view().
 *
 * This add all Fields for the Bundle to the View at runtime
 */
function ia_admin_views_views_pre_view(&$view, &$display_id, &$args) {

    if ($view->name == 'admin_views_node' && $display_id == 'system_1') {

        global $user;

        $valid_role = array_intersect($user->roles, array(
            'administrator',
            'roomify manager',
        ));

        if (empty($valid_role)){
            $view->args[] = $user->uid;
        }

        }

    return;
}
